version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: fumelli-pa-netology-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml  # Монтируем alerts.yml
      - prometheus-data:/prometheus
    networks:
      - fumelli-pa-my-netology-hw
    restart: always
    depends_on:
      - pushgateway

  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: fumelli-pa-netology-pushgateway
    ports:
      - 9091:9091
    networks:
      - fumelli-pa-my-netology-hw
    restart: always

  grafana:
    image: grafana/grafana
    container_name: fumelli-pa-netology-grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    ports:
      - 80:3000
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - fumelli-pa-my-netology-hw
    depends_on:
      - prometheus
      - alertmanager
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: fumelli-pa-netology-alertmanager
    command: --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml --cluster.listen-address=""
      - alertmanager-data:/data
    networks:
      - fumelli-pa-my-netology-hw
    depends_on:
      - prometheus
    restart: always


volumes:
  prometheus-data:
  alertmanager-data:
  grafana-data:


networks:
   fumelli-pa-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1